
# 忽略 .cocoapods 中多个 specs 源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DebugTools' do

  pod 'FLEX', :configurations => ['Debug']
  pod 'MLeaksFinder', :git => 'https://github.com/Tencent/MLeaksFinder.git', :configurations => ['Debug'], :tag => '1.1.0'

  target 'DebugToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DebugToolsUITests' do
    # Pods for testing
  end

end
