# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

workspace 'AdsSDKDemo.xcworkspace'

target 'AdsSDK' do
  #use_frameworks!
  project 'AdsSDK/AdsSDK.xcodeproj'
  pod 'SDWebImage'
end

target 'AdsSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for AdsSDKDemo
  pod 'SDWebImage'

  target 'AdsSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdsSDKDemoUITests' do
    # Pods for testing
  end

end
